config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, path_names: { sign_up: '' }
  devise_for :users, :controllers => { :registrations => 'registrations', 
                                       :sessions => 'sessions' }


  root 'snap_mentor#index'

  get 'snapmentor' => "snap_mentor#index"
  get 'bilderdaten' => "pages#images"
  get 'search_snaps'=> 'snaps#search'
  get 'impressum' => "pages#impressum"
  get 'agb' => "pages#agb"
  get 'erfolg' => "pages#erfolg"


  resources :blog_posts
  resources :snaps
  resources :categories


  get 'danke' => "charges#create"
  get 'business/bezahlen' => "charges#new"
  post 'business/bezahlen' => "charges#create"


  get 'vielendank' => "twocharges#create"
  get 'eltern/bezahlen' => "twocharges#new"
  post 'eltern/bezahlen' => "twocharges#create"
  



  
 


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_admin!, except: [:index, :show]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :body)
    end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(blog_post) do |f| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="panel panel-default">
  <div class="panel-body">
  
  <div class="form-group">
      <%= f.label :title %> 
      <%= f.text_field :title, class: "form-control", placeholder: "Titel" %>
    </div>

     <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control",placeholder: "Beschreibung" %>
    </div>


  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
</div>
</div>

<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Blog Posts</h1></br>

<% @blog_posts.each do |post| %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div class="article-title">
       <h2 align="center"> <%= link_to post.title, blog_posts_path(@blog_post)%></h2>
      </div>
      <div class="article-body">
       <p align="center"> <%= truncate(post.body, length: 100) %></p>
        
      </div>
      
      
    </div>
  </div>
</div>
<% end %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
<%= link_to 'Back', blog_posts_path %>