config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, path_names: { sign_up: '' }
  devise_for :users, :controllers => { :registrations => 'registrations', 
                                       :sessions => 'sessions' }


  root 'snap_mentor#index'

  get 'snapmentor' => "snap_mentor#index"
  get 'bilderdaten' => "pages#images"
  get 'search_snaps'=> 'snaps#search'
  get 'impressum' => "pages#impressum"
  get 'agb' => "pages#agb"
  get 'erfolg' => "pages#erfolg"


  resources :blog_posts
  resources :snaps
  resources :categories


  get 'danke' => "charges#create"
  get 'business/bezahlen' => "charges#new"
  post 'business/bezahlen' => "charges#create"


  get 'vielendank' => "twocharges#create"
  get 'eltern/bezahlen' => "twocharges#new"
  post 'eltern/bezahlen' => "twocharges#create"
  



  
 


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/snap_mentor_controller.rb
class SnapMentorController < ApplicationController
  def indexs
  end
end

app/helpers/snap_mentor_helper.rb
module SnapMentorHelper
end

app/views/snap_mentor/index.html.erb
<% if !user_signed_in? %> 
<div class="jumbotron snapyellow" align="center">
	<h1> Lerne Snapchat in nur 5 Tagen </h1>
	<h2> Täglich ein neuer Schritt, um das perfekte Snapchat-Profil zu erstellen </h2>
	<%= link_to "Anmelden", new_user_registration_path, class: "btn btn-lg btn-danger red"%>
</div>

<!-- Images start -->

<div class="row">

<div class="col-md-2">
	<div class="thumbnail one">
		</br></br></br></br></br></br></br>
	</div>
</div>

<div class="col-md-2">
	<div class="thumbnail two">
			</br></br></br></br></br></br>
	</div>
	<div>
	
			
		<%= link_to "", bilderdaten_path, class: "thumbnail three" %>
	</div>
</div>


<div class="col-md-3">
	<div>
			<%= link_to "", bilderdaten_path, class: "thumbnail four" %>
	</div>
</div>

<div class="col-md-3">
	<div class="thumbnail five">
			</br></br></br></br></br></br></br></br></br></br></br></br></br></br>
	</div>
</div>

<div class="col-md-2">
	<div class="thumbnail six">
			</br></br></br></br></br></br></br>
		</div>
</div>
</div>
<% end %>
<!-- Images end -->
<% if user_signed_in? %>
<p>
</p>
<% end %>



<div class="row">
	<div class="col-md-8">
		<div class="well distance">
			<h2 align="center"> Snapchat </h2>
			<p> Snapchat ist DIE Social-Media App. Jeder der momentan etwas zu sagen hat, tut das auf Snapchat. Die User gehen von Topmodels, über Musiker bis hin zum amerikanischen Präsidenten.</p>
			<p> Das Problem ist jedoch, dass ein Großteil der Leute, die Snapchat herunterladen komplett überfordert sind. Was zum Teufel soll ich hier machen? Was sollen die ganzen Funktionen??
			</p>
			<p> Und schließlich kommt die Frage auf: Kann ich Snapchat lernen und bringt es mir denn überhaupt etwas? </p>
			<p> Die Antwort lautet JA! Jeder kann Snapchat für sich nutzen. Man muss nur wissen wie. </p>
		</div>
	</div>

	<div class="col-md-4">
		<div style="overflow: auto;width:100%; height:260px;">
		<div class="well">
			<h2 align="center"> Nutzerstimmen </h2>
			<p>
				<blockquote>
				  <p>Für meine Firma Riddle habe ich Snapchat heruntergeladen. Aber ich wusste einfach nicht, was ich damit anfangen soll. Mit SnapMentor habe ich ganz neue Einblicke bekommen.</p>
				  <footer>Mike Hawkins <cite title="Source Title">Riddle</cite></footer>
				</blockquote>
			</p>

			<p>
				<blockquote>
				  <p>Ich habe von Snapchat als gutes Werbemittel gehört. Für meinen Verlag konnte ich es aber nicht so wirklich einsetzen – dachte ich – durch den Emailkurs habe ich tolle Ideen bekommen.</p>
				  <footer>Boris Pfeiffer <cite title="Source Title">Smiling Cat Publishing GmbH</cite></footer>
				</blockquote>
			</p>

			<p>
				<blockquote>
				  <p>Ich bin als Senior nun ganz neu mit meinem Smartphone. Da meine Enkel die ganze Zeit nur am "snapchatten" sind, wollte ich das mal ausprobieren. Aber die beiden konnten mir nicht so wirklich helfen. Ich habe gegooglet und bin hierdrauf gestoßen. Wunderbar :)</p>
				  <footer>Anne Lesch</footer>
				</blockquote>
			</p>
		</div>
	</div>
	</div>
</div>

<!-- Pricing start -->
<div class="row">
<div class="col-md-1 col-md-1-offset"></div>
<div class="col-md-10 divider">
		
	<h1 align="center" id="aftersignup"> Preise </h1>
		</br>

	<div>
		<h3 align="center"> Für jeden das richtige Angebot.</h3>
		<h4> Sie möchten als ganz normale Person verstehen, was dieses Snapchat ist, von dem die Jugend heutzutage spricht? Wollen sie auch mitreden können oder es sogar aktiv nutzen?</h4>
		<h4> Als Unternehmen Snapchat zu nutzen kann viele Vorteile haben. Man erreicht eine junge und aktive Zielgruppe und kann gleichzeitig sein Image aufwerten, da man etwas neues un innovatives als Werbemittel verwendet</h4>
		<h4> Der Snapmentor Email-Kurs ist auf beide Typen perfekt zugeschnitten. In nur 5 Tagen lernen sie hier, wie man ein echter Snapchat-Profi wird. </h4></br></br>
	</div>
</div>
<div class="col-md-1 col-md-1-offset"></div>
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-body panel-heading-privat">
				<h2 align="center"> Eltern </h2>
				<% if !user_signed_in? %><h3 align="center"> 9.99 € </h3><% end %>
			</div>
			<div class="panel-body">
				<table class="table table-hover big-text">
					<tr>
						<th>Was ist Snapchat überhaupt? </th>
					</tr>
					
					<tr>
						<th> Muss ich mir Sorgen machen? </th>
					</tr>
					<tr>
						<th> Kann ich genauso coole Sachen wie die Kids posten? </th>
					</tr>
					<tr>
						<th> Wie sehen meine Snaps besser aus?? </th>
					</tr>
					<tr>
						<th> Wem soll ich denn überhaupt folgen? </th>
					</tr></br>
				</table>
			</div>
			<div align="center" class="panel-footer">
				<%= link_to "Kaufen", eltern_bezahlen_path, class: "btn btn-default panel-heading-privat" %>
		</div>
		</div>
	</div>

	<div class="col-md-6">
		<div class="panel panel-default">
		<div class="panel-body panel-heading-business">
			<h2 align="center"> Business </h2>
			<% if !user_signed_in? %><h3 align="center"> 9.99 € </h3><% end %>
		</div>
		<div class="panel-body padding-bottom">
			<table class="table table-hover big-text">
				<tr>
					<th> Was ist Snapchat? </th>
				</tr>
				<tr>
					<th> <p>Wie nutze ich Snapchat optimal für mein Unternehmen? </p></th>
				</tr>
				<tr>
					<th> Wie erstelle ich Stories, die begeistern? </th>
				</tr>
				<tr>
					<th> Wie mache ich mein Snapchat noch besser? </th>
				</tr>
				<tr>
					<th> Welche Werbemöglichkeiten gibt es? </th>
				</tr>

			</table>
		</div>
		<div align="center" class="panel-footer">
			<%= link_to "Kaufen", business_bezahlen_path, class: "btn btn-default panel-heading-business" %>
		</div>

		</div>
	</div>
</div>
<!-- Pricing end -->

<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; <%= link_to "SnapMentor", root_path %>
			by <a href="https://www.jan-lucapfeiffer.de">Jan-Luca Pfeiffer</a>
		</small>
		<nav>
			<ul> <%= link_to "Impressum", impressum_path %></ul>
			</nav> 
		</footer>
	</div>