config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, path_names: { sign_up: '' }
  devise_for :users, :controllers => { :registrations => 'registrations', 
                                       :sessions => 'sessions' }


  root 'snap_mentor#index'

  get 'snapmentor' => "snap_mentor#index"
  get 'bilderdaten' => "pages#images"
  get 'search_snaps'=> 'snaps#search'
  get 'impressum' => "pages#impressum"
  get 'agb' => "pages#agb"
  get 'erfolg' => "pages#erfolg"


  resources :blog_posts
  resources :snaps
  resources :categories


  get 'danke' => "charges#create"
  get 'business/bezahlen' => "charges#new"
  post 'business/bezahlen' => "charges#create"


  get 'vielendank' => "twocharges#create"
  get 'eltern/bezahlen' => "twocharges#new"
  post 'eltern/bezahlen' => "twocharges#create"
  



  
 


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :snap_categories
	has_many :snaps, through: :snap_categories
	belongs_to :admin
	
	validates :name, presence: true, length: { maximum: 25, minimum: 3 }
	validates_uniqueness_of :name

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:index, :show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category_snaps = @category.snaps.paginate(page: params[:page], per_page: 5)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    @category.admin = current_admin
    if @category.save
      flash[:success] = "Category was successfully created"
      redirect_to categories_path
      redirect_to category_path(@category)
    else
      render 'new'
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    flash[:danger] = "Category was successfully deleted"
    redirect_to categories_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %>  </span>

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>

<div class="panel panel-default">
  <div class="panel-body">
  
  <div class="form-group">
      <%= f.label :name %> 
      <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
    </div>




  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
</div>
</div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="row">
<div id="categories" class="transitions-enabled">



  <% @categories.each do |category| %>
  <div class="col-md-3">
    <div class="box panel panel-default">


      

      <h3 align="center">
        <%= link_to category.name, category %>
      </h3>
      <div class="panel-footer">
      <% if category.admin = current_admin %>
      <div class="actions">

      <%= link_to edit_category_path(category) do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Edit
      <% end %>

      <%= link_to category, method: :delete, data: { confirm: 'Are you sure?' } do %>
      <span class="glyphicon glyphicon-trash"></span>
      Delete
      <% end %>

      </div>
      <% end %>
      </div>
    </div>
  </div>
  <% end %>

</div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div align="center">
 <div class="box panel panel-default" style="text-align:center">

      <div class="panel-heading" style="text-align:center">
       <h3> <%= @category.name %> </h3>
      </div>
       <div class="panel-body" style="">
 
      </div>
    </div>
  </div>
</div>