config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, path_names: { sign_up: '' }
  devise_for :users, :controllers => { :registrations => 'registrations', 
                                       :sessions => 'sessions' }


  root 'snap_mentor#index'

  get 'snapmentor' => "snap_mentor#index"
  get 'bilderdaten' => "pages#images"
  get 'search_snaps'=> 'snaps#search'
  get 'impressum' => "pages#impressum"
  get 'agb' => "pages#agb"
  get 'erfolg' => "pages#erfolg"


  resources :blog_posts
  resources :snaps
  resources :categories


  get 'danke' => "charges#create"
  get 'business/bezahlen' => "charges#new"
  post 'business/bezahlen' => "charges#create"


  get 'vielendank' => "twocharges#create"
  get 'eltern/bezahlen' => "twocharges#new"
  post 'eltern/bezahlen' => "twocharges#create"
  



  
 


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin-nav.html.erb
   <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "SnapMentor Admin", root_path,class: "navbar-brand"%>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-left">
          	<li><%= link_to "Alle Snaps", snaps_path%></li>
          	<li><%= link_to "Alle Kategorien", categories_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
          	<li><%= link_to "Neuer Snap", new_snap_path %> </li>
          	<li><%= link_to "Neue Kategorie", new_category_path %></li>
            <li><%= link_to "Neuer Post", new_blog_post_path %></li>
          	<li><%= link_to "Abmelden", destroy_admin_session_path, method: :delete %>
	
           
          </ul>
        </div>
      </div>
    </div>

app/views/layouts/_nav.html.erb
   <div class="navbar navbar-default ">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <div class="navbar-brand">
          <%= link_to image_tag("logo.png"), root_path %>
        </div>

        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">

            
            <li><%= link_to "Snaps", snaps_path %></li>
            <li><%= link_to "Snap-Blog", blog_posts_path %></li>
            <li><% link_to "Mentor", snapmentor_path %></li>


         


           
          </ul>

          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li> <%= link_to "Abmelden", destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>


        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SnapMentor" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= javascript_include_tag "application" %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-86169454-1', 'auto');
      ga('send', 'pageview');
    </script>



  </head>

  <body>



  <% if admin_signed_in? %>
    <%= render "layouts/admin-nav" %>
  <% else %> 
    <%= render 'layouts/nav' %>
  <% end %>

 <div class="container-fluid">
   <div class="row">
    <div class="col-md-12">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>

      <%= yield %>
    </div>
  </div><!--/row-->
  
</div> <!-- /container -->

  </body>
</html>